/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerRouteRouteImport } from './routes/_organizer/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OrganizerCreateEventIndexRouteImport } from './routes/_organizer/create-event/index'
import { Route as OrganizerOverviewIndexRouteImport } from './routes/_organizer/overview/index'
import { Route as OrganizerOverviewEventIdRouteImport } from './routes/_organizer/overview/$eventId'
import { Route as AttendeeAccessAccessTokenRouteImport } from './routes/attendee/access/$accessToken'
import { Route as AttendeeTestTestTokenRouteImport } from './routes/attendee/test/$testToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRouteRoute = OrganizerRouteRouteImport.update({
  id: '/_organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerCreateEventIndexRoute =
  OrganizerCreateEventIndexRouteImport.update({
    id: '/create-event/',
    path: '/create-event/',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)
const OrganizerOverviewIndexRoute = OrganizerOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const OrganizerOverviewEventIdRoute =
  OrganizerOverviewEventIdRouteImport.update({
    id: '/overview/$eventId',
    path: '/overview/$eventId',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)
const AttendeeAccessAccessTokenRoute =
  AttendeeAccessAccessTokenRouteImport.update({
    id: '/attendee/access/$accessToken',
    path: '/attendee/access/$accessToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttendeeTestTestTokenRoute = AttendeeTestTestTokenRouteImport.update({
  id: '/attendee/test/$testToken',
  path: '/attendee/test/$testToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/overview/$eventId': typeof OrganizerOverviewEventIdRoute
  '/attendee/access/$accessToken': typeof AttendeeAccessAccessTokenRoute
  '/attendee/test/$testToken': typeof AttendeeTestTestTokenRoute
  '/create-event/': typeof OrganizerCreateEventIndexRoute
  '/overview/': typeof OrganizerOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/overview/$eventId': typeof OrganizerOverviewEventIdRoute
  '/attendee/access/$accessToken': typeof AttendeeAccessAccessTokenRoute
  '/attendee/test/$testToken': typeof AttendeeTestTestTokenRoute
  '/create-event': typeof OrganizerCreateEventIndexRoute
  '/overview': typeof OrganizerOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_organizer': typeof OrganizerRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_organizer/overview/$eventId': typeof OrganizerOverviewEventIdRoute
  '/attendee/access/$accessToken': typeof AttendeeAccessAccessTokenRoute
  '/attendee/test/$testToken': typeof AttendeeTestTestTokenRoute
  '/_organizer/create-event/': typeof OrganizerCreateEventIndexRoute
  '/_organizer/overview/': typeof OrganizerOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/overview/$eventId'
    | '/attendee/access/$accessToken'
    | '/attendee/test/$testToken'
    | '/create-event/'
    | '/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/overview/$eventId'
    | '/attendee/access/$accessToken'
    | '/attendee/test/$testToken'
    | '/create-event'
    | '/overview'
  id:
    | '__root__'
    | '/'
    | '/_organizer'
    | '/login/'
    | '/_organizer/overview/$eventId'
    | '/attendee/access/$accessToken'
    | '/attendee/test/$testToken'
    | '/_organizer/create-event/'
    | '/_organizer/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRouteRoute: typeof OrganizerRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  AttendeeAccessAccessTokenRoute: typeof AttendeeAccessAccessTokenRoute
  AttendeeTestTestTokenRoute: typeof AttendeeTestTestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer': {
      id: '/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer/create-event/': {
      id: '/_organizer/create-event/'
      path: '/create-event'
      fullPath: '/create-event/'
      preLoaderRoute: typeof OrganizerCreateEventIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/_organizer/overview/': {
      id: '/_organizer/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OrganizerOverviewIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/_organizer/overview/$eventId': {
      id: '/_organizer/overview/$eventId'
      path: '/overview/$eventId'
      fullPath: '/overview/$eventId'
      preLoaderRoute: typeof OrganizerOverviewEventIdRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/attendee/access/$accessToken': {
      id: '/attendee/access/$accessToken'
      path: '/attendee/access/$accessToken'
      fullPath: '/attendee/access/$accessToken'
      preLoaderRoute: typeof AttendeeAccessAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendee/test/$testToken': {
      id: '/attendee/test/$testToken'
      path: '/attendee/test/$testToken'
      fullPath: '/attendee/test/$testToken'
      preLoaderRoute: typeof AttendeeTestTestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizerRouteRouteChildren {
  OrganizerOverviewEventIdRoute: typeof OrganizerOverviewEventIdRoute
  OrganizerCreateEventIndexRoute: typeof OrganizerCreateEventIndexRoute
  OrganizerOverviewIndexRoute: typeof OrganizerOverviewIndexRoute
}

const OrganizerRouteRouteChildren: OrganizerRouteRouteChildren = {
  OrganizerOverviewEventIdRoute: OrganizerOverviewEventIdRoute,
  OrganizerCreateEventIndexRoute: OrganizerCreateEventIndexRoute,
  OrganizerOverviewIndexRoute: OrganizerOverviewIndexRoute,
}

const OrganizerRouteRouteWithChildren = OrganizerRouteRoute._addFileChildren(
  OrganizerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRouteRoute: OrganizerRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  AttendeeAccessAccessTokenRoute: AttendeeAccessAccessTokenRoute,
  AttendeeTestTestTokenRoute: AttendeeTestTestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
