/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedCreateEventIndexRouteImport } from './routes/_authenticated/create-event/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedOverviewEventIdRouteImport } from './routes/_authenticated/overview/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateEventIndexRoute =
  AuthenticatedCreateEventIndexRouteImport.update({
    id: '/create-event/',
    path: '/create-event/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewEventIdRoute =
  AuthenticatedOverviewEventIdRouteImport.update({
    id: '/overview/$eventId',
    path: '/overview/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/overview/$eventId': typeof AuthenticatedOverviewEventIdRoute
  '/create-event/': typeof AuthenticatedCreateEventIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/overview/$eventId': typeof AuthenticatedOverviewEventIdRoute
  '/create-event': typeof AuthenticatedCreateEventIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/overview/$eventId': typeof AuthenticatedOverviewEventIdRoute
  '/_authenticated/create-event/': typeof AuthenticatedCreateEventIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login/' | '/overview/$eventId' | '/create-event/' | '/overview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/overview/$eventId' | '/create-event' | '/overview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login/'
    | '/_authenticated/overview/$eventId'
    | '/_authenticated/create-event/'
    | '/_authenticated/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-event/': {
      id: '/_authenticated/create-event/'
      path: '/create-event'
      fullPath: '/create-event/'
      preLoaderRoute: typeof AuthenticatedCreateEventIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/$eventId': {
      id: '/_authenticated/overview/$eventId'
      path: '/overview/$eventId'
      fullPath: '/overview/$eventId'
      preLoaderRoute: typeof AuthenticatedOverviewEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOverviewEventIdRoute: typeof AuthenticatedOverviewEventIdRoute
  AuthenticatedCreateEventIndexRoute: typeof AuthenticatedCreateEventIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOverviewEventIdRoute: AuthenticatedOverviewEventIdRoute,
  AuthenticatedCreateEventIndexRoute: AuthenticatedCreateEventIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
